"""Drawing layer: geometry, styles, primitives, canvas.

Knows nothing about physics, schemas or documents — everything above builds
on this vocabulary rather than formatting SVG strings directly.
"""

from physics_svg.draw.canvas import DEFAULT_PADDING, SCREEN_SCALE, Canvas
from physics_svg.draw.geometry import (
    IDENTITY,
    ORIGIN,
    BBox,
    Pt,
    Transform,
    angle_between,
    direction,
    polar,
    union_all,
)
from physics_svg.draw.medium import SHEET, Medium
from physics_svg.draw.nodes import (
    Circle,
    Ellipse,
    Group,
    Line,
    Node,
    Path,
    PathBuilder,
    Polyline,
    Raw,
    Rect,
    Text,
    Unsupported,
    arc,
)
from physics_svg.draw.style import (
    BLACK,
    BODY,
    DASH,
    FRAME,
    GREY,
    GREY_FAINT,
    GREY_LIGHT,
    GREY_STRONG,
    GRID,
    GRID_FINE,
    HAIR,
    HEAVY,
    LINE,
    OUTLINE,
    SOLID,
    THIN,
    WHITE,
    Style,
)
from physics_svg.draw.text import (
    FONT_STACK,
    clean,
    esc,
    fixed,
    num,
    svg_text,
    text_width,
)

__all__ = [
    "BBox",
    "BLACK",
    "BODY",
    "Canvas",
    "Circle",
    "DASH",
    "DEFAULT_PADDING",
    "Ellipse",
    "FONT_STACK",
    "FRAME",
    "GREY",
    "GREY_FAINT",
    "GREY_LIGHT",
    "GREY_STRONG",
    "GRID",
    "GRID_FINE",
    "Group",
    "HAIR",
    "HEAVY",
    "IDENTITY",
    "LINE",
    "Line",
    "Medium",
    "Node",
    "ORIGIN",
    "OUTLINE",
    "Path",
    "PathBuilder",
    "Polyline",
    "Pt",
    "Raw",
    "Rect",
    "SCREEN_SCALE",
    "SHEET",
    "SOLID",
    "Style",
    "THIN",
    "Text",
    "Unsupported",
    "Transform",
    "WHITE",
    "angle_between",
    "arc",
    "direction",
    "clean",
    "esc",
    "fixed",
    "num",
    "polar",
    "svg_text",
    "text_width",
    "union_all",
]
